package mensaje;

public enum TipoMensaje {
	CONEXION, CONF_CONEXION, LISTA_USUARIOS, CONF_LISTA_USUARIOS, PEDIR_PROD, EMITIR_PROD,
	PREPARADO_C_S, PREPARADO_S_C, CERRAR_CONEX, CONF_CERRAR_CONEX, NO_EXISTENTE, PEDIR_USUARIO,YALOTIENES, RECIBIR_CATEDRA, CONFRECIBIR_CATEDRA,
	MANDAR_REFRAN,CONF_MANDAR_REFRAN, YA_LOGUEADO
}
